backend:
  name: github
  repo: feelthatvib3/insbyre
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'products'
    label: 'Товары'
    folder: 'src/shared/data/products'
    create: true
    slug: '{{slug}}'
    identifier_field: 'slug'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'Название', name: 'name', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Артикул', name: 'sku', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Цена', name: 'price', widget: 'number' }
      - label: 'Категории'
        name: 'categories'
        widget: 'list'
        field:
          label: 'Категория'
          name: 'category'
          widget: 'select'
          options: ['new', 'top', 'bottom', 'accessories']
      - label: 'Размеры'
        name: 'sizes'
        widget: 'list'
        summary: '{{fields.size}} — {{fields.inStock}}'
        required: false
        fields:
          - { label: 'Размер', name: 'size', widget: 'select', options: [XS, S, M, L, XL, XXL] }
          - { label: 'В наличии', name: 'inStock', widget: 'boolean', default: true }
      - { label: 'В наличии', name: 'inStock', widget: 'boolean', default: true }
      - label: 'Изображения'
        name: 'images'
        widget: 'list'
        field:
          label: 'Изображение'
          name: 'image'
          widget: 'image'
      - { label: 'Превью', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Уход за изделием', name: 'care', widget: 'text', required: false }
      - { label: 'Доставка', name: 'shipping', widget: 'text', required: false }
      - { label: 'Посадка', name: 'fit', widget: 'text', required: false }
      - { label: 'Материалы', name: 'materials', widget: 'text', required: false }
      - { label: 'Возврат', name: 'returns', widget: 'text', required: false }
      - { label: 'Дата создания', name: 'createdAt', widget: 'datetime' }
      - {
          label: 'Дата обновления',
          name: 'updatedAt',
          widget: 'datetime',
          default: '{{now}}',
          required: false
        }
  - name: 'categories'
    label: 'Категории'
    folder: 'src/shared/data/categories'
    create: true
    slug: '{{slug}}'
    identifier_field: 'slug'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'Название', name: 'label', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Порядок', name: 'order', widget: 'number' }
